name: Test Token Access

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check if secret is available
        run: |
          if [ -z "${{ secrets.PAT_TOKEN }}" ]; then
            echo "❌ O segredo PAT_TOKEN NÃO está definido."
            exit 1
          else
            echo "✅ O segredo PAT_TOKEN está disponível!"
          fi
